name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Elige la versión de Python que estás utilizando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si tienes un archivo de requisitos, asegúrate de que esté presente

    - name: Run unit tests
      run: python -m unittest calculadora_test.py

Con esta configuración, las pruebas unitarias se ejecutarán cada vez que haya un pull request dirigido a la rama main. Esto permite que las pruebas se ejecuten antes de que se realice el merge a la rama principal, lo que garantiza que el código integrado en main cumpla con las pruebas definidas.
