name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Actualización a la versión 3
      with:
        fetch-depth: 0  # Necesario para obtener todas las ramas y etiquetas para los pull requests

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run unit tests
      run: python -m unittest calculadora_test.py
